@echo off
echo Starting SENTINEL...
echo.
echo Step 1: Starting Python API...
start cmd /k "cd C:\Users\eshan\sentinel && venv\Scripts\activate && python api.py"
timeout /t 3
echo Step 2: Starting Background Scheduler...
start cmd /k "cd C:\Users\eshan\sentinel && venv\Scripts\activate && python scheduler.py"
timeout /t 2
echo Step 3: Starting Dashboard...
start cmd /k "cd C:\Users\eshan\sentinel-dashboard && npm start"
echo.
echo SENTINEL is starting...
echo Open http://localhost:3000 in your browser
pause